"$schema" = "https://starship.rs/config-schema.json"

palette = "terminal"
add_newline = true

format = """
[╭](fg:current_line)\
$os\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$bun\
$deno\
$aws\
$cmd_duration\
$shell\
$line_break\
$character\
"""

[palettes.terminal]
# Auto-managed from `~/.config/kitty/theme.conf` by `~/.config/starship/update-palette`.
# --- palette:auto start ---
foreground = '#b7bcb9'
background = '#161718'
current_line = '#393b3b'
primary = '#2a2e33'
box = '#393b3b'
blue = '#6d90b0'
cyan = '#7fbeb3'
green = '#b3be5a'
orange = '#e5894f'
pink = '#6e4f79'
purple = '#a07eab'
red = '#b74d50'
yellow = '#e3b55e'
# --- palette:auto end ---

[fill]
symbol = "─"
style = "fg:current_line"

[os]
format = "(fg:current_line)[](fg:red)[$symbol ](fg:primary bg:red)[](fg:red)"
disabled = false

[os.symbols]
Macos = ""
Unknown = ""

[directory]
format = "[─](fg:current_line)[](fg:pink)[󰷏 ](fg:primary bg:pink)[](fg:pink bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[](fg:box)"
home_symbol = " ~/"
truncation_symbol = " "
truncation_length = 2
truncate_to_repo = true
read_only = "󱧵 "
read_only_style = ""

[git_branch]
format = "[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $branch](fg:foreground bg:box)"
symbol = " "

[git_status]
format = "[( $all_status)](fg:foreground bg:box)[](fg:box)"

[nodejs]
format = "[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)"
symbol = " "
detect_files = ["package.json", ".node-version", "!bunfig.toml", "!bun.lockb"]

[bun]
format = "[─](fg:current_line)[](fg:yellow)[$symbol](fg:primary bg:yellow)[](fg:yellow bg:box)[ $version](fg:foreground bg:box)[](fg:box)"
symbol = "bun "

[deno]
format = "[─](fg:current_line)[](fg:cyan)[$symbol](fg:primary bg:cyan)[](fg:cyan bg:box)[ $version](fg:foreground bg:box)[](fg:box)"
symbol = "deno "

[aws]
format = "[─](fg:current_line)[](fg:purple)[$symbol](fg:primary bg:purple)[](fg:purple bg:box)[ $profile](fg:foreground bg:box)[](fg:box)"
symbol = "󰅟 "
disabled = true

[cmd_duration]
min_time = 500
format = "[─](fg:current_line)[](fg:orange)[󰔟 ](fg:primary bg:orange)[](fg:orange bg:box)[ $duration ](fg:foreground bg:box)[](fg:box)"

[shell]
format = "[─](fg:current_line)[](fg:blue)[ ](fg:primary bg:blue)[](fg:blue bg:box)[ $indicator](fg:foreground bg:box)[](fg:box)"
disabled = false

[time]
disabled = true

[username]
disabled = true

[kubernetes]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

[character]
format = """
[│](fg:current_line)
[╰─$symbol](fg:current_line) """
success_symbol = "[❯](fg:bold green)"
error_symbol = "[❯](fg:bold red)"
